sonar.projectKey=Actividad-Evaluativa-2
sonar.projectName=Actividad Evaluativa 2
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_dc6d0ae3aebaed27d8f5ebdac268b2aa01c2a638
